# -*- coding: utf-8 -*-
"""inference.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W8gAj7RfsAMsnVyhp0eQioHN3p2-5uBr
"""

import pandas as pd
import joblib
from google.colab import files
import os

pipeline = joblib.load('/content/best_model_pipeline (1).pkl')
print("✅ Pipeline loaded successfully!")

df_new = pd.read_csv('/content/cleaned_heart_disease (1).csv')
print("Columns in new data:", df_new.columns.tolist())

#target_col_index = 9
target_col_name = '13' # Assuming '9' is the target column name
X_new = df_new.drop(target_col_name, axis=1)

predictions = pipeline.predict(X_new)
print("✅ Predictions completed!")

os.makedirs('./Data', exist_ok=True)
output_df = pd.DataFrame(predictions, columns=['Prediction'])
output_path = './Data/predictions.csv'
output_df.to_csv(output_path, index=False)
print(f"🎯✅ Predictions saved to {output_path}")

files.download(output_path)